# Generated by Django 5.2.8 on 2025-11-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taqueria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
